config/routes.rb
R20130319PhotoAlbm::Application.routes.draw do
  root :to => 'home#index'
  resources :albums, :only => [:new, :create, :show] do
    member do
      get :filter
    end
  end


      #get albums/id/filter
  resources :photos,  :only => [:new, :create]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  attr_accessible :name
  has_many :photos
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  url        :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  album_id   :integer
#

class Photo < ActiveRecord::Base
  attr_accessible :name, :url, :remote_url_url
  belongs_to :album
  mount_uploader :url, PicUploader
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
  end

  def create
    Album.create(params[:album])
    @albums = Album.order(:name)
  end

  def show
      album = Album.find(params[:id])
      @photos= album.photos
  end

  def filter
    album = Album.find(params[:id])
    @photos = album.photos.limit(params[:count]) #JS calls look for JS files.
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @albums = Album.order(:name)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

def new

@photo = Photo.new
end

def create
photo = Photo.create(params[:photo])
  album = Album.find(params[:album_id]) #:album id was shoved into the new form so now we can find that object.
  album.photos << photo
  @photos =  album.photos
  end

def show
  album = Album.find(params[:id])
  @photos = album.photos
  end
end


#when page first loads , or when u create a photo. instances of the show page.

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_albums.html.haml
%table
  %tr
    %th Album Name
    %th Photo Count
  - @albums.each do |album|
    %tr
      %td= link_to(album.name, album, :class => 'button tiny radius success')
      %td= album.photos.count

app/views/albums/_form.html.haml
.row
  .large-3.columns
    = form_for @album, :remote => true do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = link_to 'Cancel', '#', :'data-clear-form' => true, :class => 'button tiny radius alert'
      = f.submit nil, :class => 'button tiny radius success'
  .large-9.columns

app/views/albums/create.js.erb
$('#form').empty();
$('#albums').empty().append('<%=j render :partial => 'albums' %>');

app/views/albums/filter.js.erb
$('#form').empty()
$('#photos').empty().append('<%=j render :partial => 'photos/photos' %>');

app/views/albums/new.js.erb
$('#form').empty().append('<%=j render :partial => 'form' %>');

app/views/albums/show.html.haml
#album{:'data-album_id' => params[:id]}
.row
  .large-2-columns
    = link_to('New Photo', new_photo_path(:album_id => params[:id]) , :remote => true, :class => 'button tiny radius')
  .large-2.columns
    #slider
  .large-8.columns
#form
#photos
  = render :partial => 'photos/photos'

//JQ call is album-id

app/views/home/index.html.haml
= link_to('New Album', new_album_path, :remote => true, :class => 'button tiny radius')
#form
#albums
  = render :partial => 'albums/albums'

app/views/layouts/_body.html.erb
<div class="row">
  <div class="large-12 columns">
    <%= yield %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-6 columns">
        <h6 class='subheader'>&copy; Chyld Medford</h6>
      </div>
      <div class="large-6 columns">
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="nav-bar right">
     <ul class="button-group">
       <li><%= link_to('Home', root_path, :class => 'button tiny') %></li>
      </ul>
    </div>
    <h2 class='subheader'>albm</h2>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>albm</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='nav'><%= render :partial => 'layouts/nav' %></div>
  <div id='body'><%= render :partial => 'layouts/body' %></div>
  <div id='footer'><%= render :partial => 'layouts/footer' %></div>

  <script>
  $(document).foundation();
  </script>
</body>
</html>

app/views/photos/_form.html.haml
.row
  .large-3.columns
    = form_for @photo, :html => {:multipart => true}, :remote => true do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :url
      = f.file_field :url
      = f.text_field :remote_url_url
      = hidden_field_tag :album_id, params[:album_id]
      = link_to 'Cancel', '#', :'data-clear-form' => true, :class => 'button tiny radius alert'
      = f.submit nil, :class => 'button tiny radius success'
  .large-9.columns

app/views/photos/_photos.html.haml
%ul
  - @photos.each do |photo|
    .photo= image_tag(photo.url.thumb.url)

app/views/photos/create.js.erb
$('#form').empty();
$('#photos').empty.append('<%=j render :partial => 'photos' %>');

app/views/photos/new.js.erb
$('#form').empty().append('<%=j render :partial => 'form' %>');